import type { Locale } from '@/i18n/locales';

export interface EquipmentPageStrings {
  badge: string;
  heroTitle1: string;
  heroTitle2: string;
  heroBody: string;
  tags: string[];
  facilityScale: string;
  facilityOverview: string;
  equipmentConfig: string;
  locationLabel: string;
  locationTitle: string;
  locationBody: string;
  contactUs: string;
  showcaseSection: string;
  showcaseTitle: string;
  modelPrefix: string;
  specsSection: string;
  specsTitle: string;
  tableHeaders: string[];
  kpis: { value: string; label: string; sub: string }[];
}

const en: EquipmentPageStrings = {
  badge: 'Production Excellence',
  heroTitle1: 'Industrial-Grade', heroTitle2: 'Extraction Facility',
  heroBody: 'Our Chuxiong, Yunnan facility is equipped with extraction tanks, chromatography columns, concentrators, and analytical systems — supporting CBD raw material production.',
  tags: ['Extraction', 'Chromatography', 'Concentration', 'Automation'],
  facilityScale: 'Facility Scale',
  facilityOverview: 'Facility Overview', equipmentConfig: 'Equipment Configuration',
  locationLabel: 'Location', locationTitle: 'Chuxiong, Yunnan\nProduction Facility',
  locationBody: 'Professional extraction and processing facility supporting CBD raw material production.',
  contactUs: 'Contact Us',
  showcaseSection: 'Equipment Showcase', showcaseTitle: 'Precision-Engineered at Every Stage',
  modelPrefix: 'Model:',
  specsSection: 'Full Specifications', specsTitle: 'Equipment Overview Table',
  tableHeaders: ['Equipment Name', 'Model Range', 'Process Function', 'Notes'],
  kpis: [
    { value: '20', label: 'Extraction Tanks', sub: '6 m³ multi-function' },
    { value: '26', label: 'Chromatography Columns', sub: 'Gradient elution' },
    { value: '10', label: 'Concentrators', sub: '2 000 L single/double-effect' },
    { value: 'HPLC', label: 'In-house Analytics', sub: 'Cannabinoid profiling' },
  ],
};

export const equipmentPageStrings: Record<Locale, EquipmentPageStrings> = {
  en,
  de: { ...en,
    badge: 'Produktionsexzellenz',
    heroTitle1: 'Industrielle', heroTitle2: 'Extraktionsanlage',
    heroBody: 'Unsere Anlage in Chuxiong, Yunnan ist mit Extraktionstanks, Chromatographiesäulen, Konzentratoren und Analysesystemen ausgestattet — für die CBD-Rohstoffproduktion.',
    tags: ['Extraktion', 'Chromatographie', 'Konzentration', 'Automatisierung'],
    facilityScale: 'Anlagengröße',
    facilityOverview: 'Anlagenübersicht', equipmentConfig: 'Anlagenkonfiguration',
    locationLabel: 'Standort', locationTitle: 'Chuxiong, Yunnan\nProduktionsanlage',
    locationBody: 'Professionelle Extraktions- und Verarbeitungsanlage für die CBD-Rohstoffproduktion.',
    contactUs: 'Kontakt',
    showcaseSection: 'Anlagenpräsentation', showcaseTitle: 'Präzisionstechnik in jeder Phase',
    modelPrefix: 'Modell:',
    specsSection: 'Vollständige Spezifikationen', specsTitle: 'Anlagenübersichtstabelle',
    tableHeaders: ['Anlagenname', 'Modellbereich', 'Prozessfunktion', 'Hinweise'],
    kpis: [
      { value: '20', label: 'Extraktionstanks', sub: '6 m³ Multifunktion' },
      { value: '26', label: 'Chromatographiesäulen', sub: 'Gradientenelution' },
      { value: '10', label: 'Konzentratoren', sub: '2 000 L Einfach-/Doppeleffekt' },
      { value: 'HPLC', label: 'Hauseigene Analytik', sub: 'Cannabinoid-Profilierung' },
    ],
  },
  fr: { ...en,
    badge: "Excellence de production",
    heroTitle1: 'Installation', heroTitle2: "d'extraction industrielle",
    heroBody: "Notre installation à Chuxiong, Yunnan est équipée de cuves d'extraction, colonnes de chromatographie, concentrateurs et systèmes analytiques — soutenant la production de matières premières CBD.",
    tags: ['Extraction', 'Chromatographie', 'Concentration', 'Automatisation'],
    facilityScale: "Échelle de l'installation",
    facilityOverview: "Vue d'ensemble", equipmentConfig: 'Configuration des équipements',
    locationLabel: 'Localisation', locationTitle: 'Chuxiong, Yunnan\nSite de production',
    locationBody: "Installation professionnelle d'extraction et de traitement soutenant la production de matières premières CBD.",
    contactUs: 'Contactez-nous',
    showcaseSection: 'Présentation des équipements', showcaseTitle: 'Ingénierie de précision à chaque étape',
    modelPrefix: 'Modèle :',
    specsSection: 'Spécifications complètes', specsTitle: "Tableau récapitulatif des équipements",
    tableHeaders: ['Nom de l\'équipement', 'Gamme de modèles', 'Fonction du processus', 'Notes'],
    kpis: [
      { value: '20', label: "Cuves d'extraction", sub: '6 m³ multifonction' },
      { value: '26', label: 'Colonnes de chromatographie', sub: 'Élution en gradient' },
      { value: '10', label: 'Concentrateurs', sub: '2 000 L simple/double effet' },
      { value: 'HPLC', label: 'Analytique interne', sub: 'Profilage des cannabinoïdes' },
    ],
  },
  es: { ...en,
    badge: 'Excelencia en producción',
    heroTitle1: 'Instalación de', heroTitle2: 'extracción industrial',
    heroBody: 'Nuestra instalación en Chuxiong, Yunnan está equipada con tanques de extracción, columnas de cromatografía, concentradores y sistemas analíticos — respaldando la producción de materias primas CBD.',
    tags: ['Extracción', 'Cromatografía', 'Concentración', 'Automatización'],
    facilityScale: 'Escala de la instalación',
    facilityOverview: 'Vista general', equipmentConfig: 'Configuración de equipos',
    locationLabel: 'Ubicación', locationTitle: 'Chuxiong, Yunnan\nInstalación de producción',
    locationBody: 'Instalación profesional de extracción y procesamiento para la producción de materias primas CBD.',
    contactUs: 'Contáctenos',
    showcaseSection: 'Presentación de equipos', showcaseTitle: 'Ingeniería de precisión en cada etapa',
    modelPrefix: 'Modelo:',
    specsSection: 'Especificaciones completas', specsTitle: 'Tabla resumen de equipos',
    tableHeaders: ['Nombre del equipo', 'Rango de modelo', 'Función del proceso', 'Notas'],
    kpis: [
      { value: '20', label: 'Tanques de extracción', sub: '6 m³ multifunción' },
      { value: '26', label: 'Columnas de cromatografía', sub: 'Elución en gradiente' },
      { value: '10', label: 'Concentradores', sub: '2 000 L simple/doble efecto' },
      { value: 'HPLC', label: 'Analítica interna', sub: 'Perfilado de cannabinoides' },
    ],
  },
  it: { ...en,
    badge: 'Eccellenza produttiva',
    heroTitle1: 'Impianto di', heroTitle2: 'estrazione industriale',
    heroBody: 'Il nostro impianto a Chuxiong, Yunnan è dotato di serbatoi di estrazione, colonne cromatografiche, concentratori e sistemi analitici — a supporto della produzione di materie prime CBD.',
    tags: ['Estrazione', 'Cromatografia', 'Concentrazione', 'Automazione'],
    facilityScale: "Scala dell'impianto",
    facilityOverview: "Panoramica dell'impianto", equipmentConfig: 'Configurazione attrezzature',
    locationLabel: 'Sede', locationTitle: 'Chuxiong, Yunnan\nImpianto di produzione',
    locationBody: 'Impianto professionale di estrazione e lavorazione a supporto della produzione di materie prime CBD.',
    contactUs: 'Contattaci',
    showcaseSection: 'Presentazione attrezzature', showcaseTitle: 'Ingegneria di precisione in ogni fase',
    modelPrefix: 'Modello:',
    specsSection: 'Specifiche complete', specsTitle: 'Tabella riepilogativa attrezzature',
    tableHeaders: ['Nome attrezzatura', 'Gamma modelli', 'Funzione di processo', 'Note'],
    kpis: [
      { value: '20', label: 'Serbatoi di estrazione', sub: '6 m³ multifunzione' },
      { value: '26', label: 'Colonne cromatografiche', sub: 'Eluizione a gradiente' },
      { value: '10', label: 'Concentratori', sub: '2 000 L singolo/doppio effetto' },
      { value: 'HPLC', label: 'Analitica interna', sub: 'Profilazione cannabinoidi' },
    ],
  },
  pt: { ...en,
    badge: 'Excelência em produção',
    heroTitle1: 'Instalação de', heroTitle2: 'extração industrial',
    heroBody: 'Nossa instalação em Chuxiong, Yunnan é equipada com tanques de extração, colunas de cromatografia, concentradores e sistemas analíticos — apoiando a produção de matérias-primas CBD.',
    tags: ['Extração', 'Cromatografia', 'Concentração', 'Automação'],
    facilityScale: 'Escala da instalação',
    facilityOverview: 'Visão geral', equipmentConfig: 'Configuração de equipamentos',
    locationLabel: 'Localização', locationTitle: 'Chuxiong, Yunnan\nInstalação de produção',
    locationBody: 'Instalação profissional de extração e processamento para a produção de matérias-primas CBD.',
    contactUs: 'Fale conosco',
    showcaseSection: 'Apresentação de equipamentos', showcaseTitle: 'Engenharia de precisão em cada etapa',
    modelPrefix: 'Modelo:',
    specsSection: 'Especificações completas', specsTitle: 'Tabela resumo de equipamentos',
    tableHeaders: ['Nome do equipamento', 'Faixa de modelo', 'Função do processo', 'Notas'],
    kpis: [
      { value: '20', label: 'Tanques de extração', sub: '6 m³ multifunção' },
      { value: '26', label: 'Colunas de cromatografia', sub: 'Eluição em gradiente' },
      { value: '10', label: 'Concentradores', sub: '2 000 L simples/duplo efeito' },
      { value: 'HPLC', label: 'Analítica interna', sub: 'Perfil de canabinoides' },
    ],
  },
  ja: { ...en,
    badge: '生産の卓越性',
    heroTitle1: '産業グレード', heroTitle2: '抽出施設',
    heroBody: 'Chuxiong, Yunnanの施設には、抽出タンク、クロマトグラフィーカラム、濃縮器、分析システムを備え、CBD原料の生産を支えています。',
    tags: ['抽出', 'クロマトグラフィー', '濃縮', '自動制御'],
    facilityScale: '施設規模',
    facilityOverview: '施設概要', equipmentConfig: '設備構成',
    locationLabel: '所在地', locationTitle: 'Chuxiong, Yunnan\n生産施設',
    locationBody: 'CBD原料生産を支える専門的な抽出・加工施設です。',
    contactUs: 'お問い合わせ',
    showcaseSection: '設備紹介', showcaseTitle: 'すべての工程に精密エンジニアリング',
    modelPrefix: 'モデル:',
    specsSection: '全仕様', specsTitle: '設備一覧表',
    tableHeaders: ['設備名', 'モデル範囲', 'プロセス機能', '備考'],
    kpis: [
      { value: '20', label: '抽出タンク', sub: '6 m³ 多機能' },
      { value: '26', label: 'クロマトグラフィーカラム', sub: 'グラジエント溶出' },
      { value: '10', label: '濃縮器', sub: '2 000 L 単効/複効' },
      { value: 'HPLC', label: '自社分析', sub: 'カンナビノイドプロファイリング' },
    ],
  },
  fi: { ...en,
    badge: 'Tuotannon erinomaisuus',
    heroTitle1: 'Teollisuustason', heroTitle2: 'uuttolaitos',
    heroBody: 'Chuxiongin, Yunnanin laitoksemme on varustettu uuttosäiliöillä, kromatografiakolumneilla, konsentraattoreilla ja analyysijärjestelmillä — tukien CBD-raaka-aineiden tuotantoa.',
    tags: ['Uutto', 'Kromatografia', 'Konsentrointi', 'Automaatio'],
    facilityScale: 'Laitoksen mittakaava',
    facilityOverview: 'Laitoksen yleiskatsaus', equipmentConfig: 'Laitekokoonpano',
    locationLabel: 'Sijainti', locationTitle: 'Chuxiong, Yunnan\nTuotantolaitos',
    locationBody: 'Ammattimainen uutto- ja käsittelylaitos CBD-raaka-aineiden tuotantoon.',
    contactUs: 'Ota yhteyttä',
    showcaseSection: 'Laite-esittely', showcaseTitle: 'Tarkkuustekniikkaa jokaisessa vaiheessa',
    modelPrefix: 'Malli:',
    specsSection: 'Täydelliset tekniset tiedot', specsTitle: 'Laitteiden yhteenvetotaulukko',
    tableHeaders: ['Laitteen nimi', 'Mallialue', 'Prosessitoiminto', 'Huomautukset'],
    kpis: [
      { value: '20', label: 'Uuttosäiliöt', sub: '6 m³ monitoiminen' },
      { value: '26', label: 'Kromatografiakolumnit', sub: 'Gradienttieluutio' },
      { value: '10', label: 'Konsentraattorit', sub: '2 000 L yksinkertainen/kaksoisvaikutus' },
      { value: 'HPLC', label: 'Sisäinen analytiikka', sub: 'Kannabinoidien profilointi' },
    ],
  },
};
