import type { Locale } from '@/i18n/locales';

export interface HomePageStrings {
  // Hero
  heroEyebrow: string;
  heroTitle1: string;
  heroTitle2: string;
  heroBody: string;
  requestCoa: string;
  getBulkQuote: string;
  // Trust bar
  trustHplc: string;
  trustCoa: string;
  trustPackaging: string;
  trustOem: string;
  trustExport: string;
  // Buyer Answers
  buyerAnswersEyebrow: string;
  buyerAnswersTitle: string;
  qa: { question: string; answer: string }[];
  // Business Scope
  scopeEyebrow: string;
  scopeTitle1: string;
  scopeTitle2: string;
  rawMaterialTitle: string;
  rawMaterialBody: string;
  rawMaterialCta: string;
  oemTitle: string;
  oemBody: string;
  oemCta: string;
  techTitle: string;
  techBody: string;
  techCta: string;
  // KPI row
  kpiAnalytical: { value: string; label: string; sub: string };
  kpiDocumentation: { value: string; label: string; sub: string };
  kpiPackaging: { value: string; label: string; sub: string };
  kpiCooperation: { value: string; label: string; sub: string };
  // Brand Statement
  aboutEyebrow: string;
  aboutTitle1: string;
  aboutTitle2: string;
  aboutQuote: string;
  aboutQuoteAttribution: string;
  aboutPara1: string;
  aboutPara2: string;
  companyProfile: string;
  // Contact
  contactEyebrow: string;
  contactTitle1: string;
  contactTitle2: string;
  emailUs: string;
  generalInquiry: string;
  salesOem: string;
  company: string;
  location: string;
  ctaTitle: string;
  ctaBody: string;
  sendInquiry: string;
}

export const homePageStrings: Record<Locale, HomePageStrings> = {
  en: {
    heroEyebrow: 'VETRUX · Yunnan, China',
    heroTitle1: 'From Seed',
    heroTitle2: 'to Isolate',
    heroBody: 'Bulk CBD isolate for B2B buyers, with OEM/ODM support, export-ready documentation, and in-house quality-control workflows from Yunnan, China.',
    requestCoa: 'Request COA / Spec Sheet',
    getBulkQuote: 'Get Bulk Quote',
    trustHplc: 'In-house HPLC',
    trustCoa: 'COA / SDS support',
    trustPackaging: '5 kg bulk packaging',
    trustOem: 'OEM/ODM available',
    trustExport: 'Export paperwork support',
    buyerAnswersEyebrow: 'Buyer Answers',
    buyerAnswersTitle: 'Bulk CBD isolate sourcing answers',
    qa: [
      {
        question: 'What does Vetrux manufacture?',
        answer: 'Vetrux manufactures bulk CBD isolate and related CBD raw material solutions for qualified B2B discussions, supported by cultivation, extraction, purification, quality-control, and packaging workflows in Yunnan, China.',
      },
      {
        question: 'Who does Vetrux serve?',
        answer: 'Vetrux serves B2B buyers, brand owners, trading companies, channel partners, and formulation teams that need bulk CBD isolate, OEM/ODM support, documentation support, and recurring supply discussions.',
      },
      {
        question: 'What documents can buyers request?',
        answer: 'Buyers can request COA, SDS, test reports, product information, commercial invoice, packing list, and export paperwork support. Availability depends on actual batch, order terms, and verification results.',
      },
      {
        question: 'Where is Vetrux based?',
        answer: 'Vetrux Biotechnology (Chuxiong) Co., Ltd. is based in Chuxiong, Yunnan, China, with CBD raw material operations connected to local cultivation, processing, quality-control, and packaging workflows.',
      },
    ],
    scopeEyebrow: 'Business Scope',
    scopeTitle1: 'End-to-end capabilities,',
    scopeTitle2: 'tailored to your needs',
    rawMaterialTitle: 'CBD Raw Material Sales',
    rawMaterialBody: 'Serving brand clients, channel partners, and trading companies with stable CBD supply. Standard supply, long-term agreements, and directed cooperation models available.',
    rawMaterialCta: 'Explore Supply',
    oemTitle: 'OEM / ODM Services',
    oemBody: 'Full-process support from raw material sourcing and formulation development to production, packaging design, and finished product delivery for your brand.',
    oemCta: 'Start a Project',
    techTitle: 'Technical Services',
    techBody: 'Cultivation management, yield optimization, extraction process refinement, cost control, and cannabinoid purification consulting.',
    techCta: 'Inquire Now',
    kpiAnalytical: { value: 'HPLC', label: 'Analytical Capability', sub: 'Quality-control support' },
    kpiDocumentation: { value: 'COA/SDS', label: 'Documentation', sub: 'By order requirements' },
    kpiPackaging: { value: '5 kg', label: 'Bulk Packaging', sub: 'PE or aluminum-foil bags' },
    kpiCooperation: { value: 'OEM/ODM', label: 'Cooperation', sub: 'B2B project support' },
    aboutEyebrow: 'About Vetrux',
    aboutTitle1: 'Quality rooted in',
    aboutTitle2: 'every step of the process',
    aboutQuote: 'We treat every kilo of isolate as if it ships under our own name. Traceability is not a label \u2014 it\u2019s how the team works.',
    aboutQuoteAttribution: '— Quality Lead, VETRUX',
    aboutPara1: 'VETRUX is built on a single conviction \u2014 that consistent batch review starts in the field, not at the bottling line. Cultivation, extraction, and in-house quality-control workflows are connected so buyer discussions can reference the same product and documentation context.',
    aboutPara2: 'From cultivation to chromatography to export packaging, VETRUX delivers a single accountable supply line for B2B partners.',
    companyProfile: 'Company Profile',
    contactEyebrow: 'Contact',
    contactTitle1: "Let's discuss",
    contactTitle2: 'your requirements',
    emailUs: 'Email Us',
    generalInquiry: 'General Inquiry',
    salesOem: 'Sales & OEM/ODM',
    company: 'Company',
    location: 'Location',
    ctaTitle: 'Ready to start a conversation?',
    ctaBody: 'Tell us about your project and our B2B team will review the details.',
    sendInquiry: 'Send Inquiry',
  },

  de: {
    heroEyebrow: 'VETRUX · Yunnan, China',
    heroTitle1: 'Vom Samen',
    heroTitle2: 'zum Isolat',
    heroBody: 'CBD-Isolat in Großmengen für B2B-Käufer, mit OEM/ODM-Support, exportfertiger Dokumentation und internen Qualitätskontrollprozessen aus Yunnan, China.',
    requestCoa: 'COA / Datenblatt anfordern',
    getBulkQuote: 'Großhandelsangebot anfragen',
    trustHplc: 'Internes HPLC-Labor',
    trustCoa: 'COA / SDS-Support',
    trustPackaging: '5-kg-Großgebinde',
    trustOem: 'OEM/ODM verfügbar',
    trustExport: 'Exportdokumentation',
    buyerAnswersEyebrow: 'Käufer-FAQ',
    buyerAnswersTitle: 'Antworten zur CBD-Isolat-Beschaffung',
    qa: [
      {
        question: 'Was stellt Vetrux her?',
        answer: 'Vetrux stellt CBD-Isolat in Großmengen und verwandte CBD-Rohstofflösungen für qualifizierte B2B-Gespräche her, unterstützt durch Anbau-, Extraktions-, Reinigungs-, Qualitätskontroll- und Verpackungsprozesse in Yunnan, China.',
      },
      {
        question: 'Wen beliefert Vetrux?',
        answer: 'Vetrux beliefert B2B-Käufer, Markeninhaber, Handelsunternehmen, Kanalpartner und Formulierungsteams, die CBD-Isolat in Großmengen, OEM/ODM-Support, Dokumentationsunterstützung und wiederkehrende Liefergespräche benötigen.',
      },
      {
        question: 'Welche Dokumente können Käufer anfordern?',
        answer: 'Käufer können COA, SDS, Prüfberichte, Produktinformationen, Handelsrechnung, Packliste und Exportdokumentationsunterstützung anfordern. Die Verfügbarkeit hängt von der tatsächlichen Charge, den Auftragsbedingungen und den Verifizierungsergebnissen ab.',
      },
      {
        question: 'Wo ist Vetrux ansässig?',
        answer: 'Vetrux Biotechnology (Chuxiong) Co., Ltd. hat seinen Sitz in Chuxiong, Yunnan, China, mit CBD-Rohstoffoperationen, die mit lokalen Anbau-, Verarbeitungs-, Qualitätskontroll- und Verpackungsprozessen verbunden sind.',
      },
    ],
    scopeEyebrow: 'Geschäftsbereich',
    scopeTitle1: 'Durchgängige Kompetenzen,',
    scopeTitle2: 'auf Ihre Anforderungen zugeschnitten',
    rawMaterialTitle: 'CBD-Rohstoffvertrieb',
    rawMaterialBody: 'Belieferung von Markenunternehmen, Kanalpartnern und Handelsgesellschaften mit stabilem CBD-Angebot. Standardlieferung, Langzeitverträge und gezielte Kooperationsmodelle verfügbar.',
    rawMaterialCta: 'Angebot erkunden',
    oemTitle: 'OEM / ODM-Dienstleistungen',
    oemBody: 'Vollständige Prozessunterstützung von der Rohstoffbeschaffung und Formulierungsentwicklung bis hin zu Produktion, Verpackungsdesign und Fertigproduktlieferung für Ihre Marke.',
    oemCta: 'Projekt starten',
    techTitle: 'Technische Dienstleistungen',
    techBody: 'Anbaumanagement, Ertragsoptimierung, Verfeinerung des Extraktionsprozesses, Kostenkontrolle und Beratung zur Cannabinoid-Reinigung.',
    techCta: 'Jetzt anfragen',
    kpiAnalytical: { value: 'HPLC', label: 'Analytische Kapazität', sub: 'Qualitätskontrolle' },
    kpiDocumentation: { value: 'COA/SDS', label: 'Dokumentation', sub: 'Nach Auftragsanforderungen' },
    kpiPackaging: { value: '5 kg', label: 'Großgebinde', sub: 'PE- oder Aluminiumfolienbeutel' },
    kpiCooperation: { value: 'OEM/ODM', label: 'Kooperation', sub: 'B2B-Projektunterstützung' },
    aboutEyebrow: 'Über Vetrux',
    aboutTitle1: 'Qualität verankert in',
    aboutTitle2: 'jedem Schritt des Prozesses',
    aboutQuote: 'Wir behandeln jedes Kilo Isolat, als würde es unter unserem eigenen Namen versandt. Rückverfolgbarkeit ist kein Label \u2014 es ist die Arbeitsweise des Teams.',
    aboutQuoteAttribution: '— Qualitätsleitung, VETRUX',
    aboutPara1: 'VETRUX basiert auf einer einzigen Überzeugung \u2014 dass eine konsistente Chargenprüfung auf dem Feld beginnt, nicht an der Abfülllinie. Anbau, Extraktion und interne Qualitätskontrollprozesse sind so verbunden, dass Käufergespräche auf denselben Produkt- und Dokumentationskontext verweisen können.',
    aboutPara2: 'Von der Kultivierung über die Chromatographie bis zur Exportverpackung liefert VETRUX eine einzige verantwortliche Versorgungslinie für B2B-Partner.',
    companyProfile: 'Unternehmensprofil',
    contactEyebrow: 'Kontakt',
    contactTitle1: 'Lassen Sie uns',
    contactTitle2: 'Ihre Anforderungen besprechen',
    emailUs: 'E-Mail senden',
    generalInquiry: 'Allgemeine Anfrage',
    salesOem: 'Vertrieb & OEM/ODM',
    company: 'Unternehmen',
    location: 'Standort',
    ctaTitle: 'Bereit für ein Gespräch?',
    ctaBody: 'Schildern Sie uns Ihr Projekt und unser B2B-Team wird die Details prüfen.',
    sendInquiry: 'Anfrage senden',
  },

  fr: {
    heroEyebrow: 'VETRUX · Yunnan, Chine',
    heroTitle1: 'De la graine',
    heroTitle2: "à l'isolat",
    heroBody: "Isolat CBD en vrac pour acheteurs B2B, avec support OEM/ODM, documentation prête à l'export et processus de contrôle qualité internes depuis Yunnan, Chine.",
    requestCoa: 'Demander COA / Fiche technique',
    getBulkQuote: 'Obtenir un devis en gros',
    trustHplc: 'HPLC en interne',
    trustCoa: 'Support COA / SDS',
    trustPackaging: 'Conditionnement 5 kg',
    trustOem: 'OEM/ODM disponible',
    trustExport: "Support documentation export",
    buyerAnswersEyebrow: 'Questions acheteurs',
    buyerAnswersTitle: "Réponses sur l'approvisionnement en isolat CBD",
    qa: [
      {
        question: 'Que fabrique Vetrux ?',
        answer: "Vetrux fabrique de l'isolat CBD en vrac et des solutions de matières premières CBD connexes pour des discussions B2B qualifiées, soutenues par des processus de culture, d'extraction, de purification, de contrôle qualité et d'emballage à Yunnan, Chine.",
      },
      {
        question: 'Qui Vetrux sert-il ?',
        answer: "Vetrux sert les acheteurs B2B, les propriétaires de marques, les sociétés commerciales, les partenaires de distribution et les équipes de formulation qui ont besoin d'isolat CBD en vrac, de support OEM/ODM, de support documentaire et de discussions d'approvisionnement récurrentes.",
      },
      {
        question: 'Quels documents les acheteurs peuvent-ils demander ?',
        answer: "Les acheteurs peuvent demander COA, SDS, rapports de test, informations produit, facture commerciale, liste de colisage et support de documentation export. La disponibilité dépend du lot réel, des conditions de commande et des résultats de vérification.",
      },
      {
        question: 'Où est basé Vetrux ?',
        answer: "Vetrux Biotechnology (Chuxiong) Co., Ltd. est basé à Chuxiong, Yunnan, Chine, avec des opérations de matières premières CBD connectées aux processus locaux de culture, de traitement, de contrôle qualité et d'emballage.",
      },
    ],
    scopeEyebrow: 'Périmètre commercial',
    scopeTitle1: 'Capacités de bout en bout,',
    scopeTitle2: 'adaptées à vos besoins',
    rawMaterialTitle: 'Vente de matières premières CBD',
    rawMaterialBody: "Service aux clients marques, partenaires de distribution et sociétés commerciales avec un approvisionnement CBD stable. Approvisionnement standard, accords à long terme et modèles de coopération dirigée disponibles.",
    rawMaterialCta: "Explorer l'offre",
    oemTitle: 'Services OEM / ODM',
    oemBody: "Support complet du processus, de l'approvisionnement en matières premières et du développement de formulations jusqu'à la production, la conception d'emballages et la livraison du produit fini pour votre marque.",
    oemCta: 'Démarrer un projet',
    techTitle: 'Services techniques',
    techBody: "Gestion de la culture, optimisation des rendements, amélioration du processus d'extraction, contrôle des coûts et conseil en purification des cannabinoïdes.",
    techCta: 'Demander maintenant',
    kpiAnalytical: { value: 'HPLC', label: 'Capacité analytique', sub: 'Support contrôle qualité' },
    kpiDocumentation: { value: 'COA/SDS', label: 'Documentation', sub: 'Selon exigences commande' },
    kpiPackaging: { value: '5 kg', label: 'Conditionnement vrac', sub: 'Sachets PE ou aluminium' },
    kpiCooperation: { value: 'OEM/ODM', label: 'Coopération', sub: 'Support projet B2B' },
    aboutEyebrow: 'À propos de Vetrux',
    aboutTitle1: 'Qualité ancrée dans',
    aboutTitle2: 'chaque étape du processus',
    aboutQuote: "Nous traitons chaque kilo d'isolat comme s'il était expédié sous notre propre nom. La traçabilité n'est pas une étiquette \u2014 c'est la façon dont l'équipe travaille.",
    aboutQuoteAttribution: '— Responsable qualité, VETRUX',
    aboutPara1: "VETRUX est fondé sur une conviction unique \u2014 que la revue cohérente des lots commence sur le terrain, pas à la ligne d'embouteillage. La culture, l'extraction et les processus internes de contrôle qualité sont connectés afin que les discussions avec les acheteurs puissent référencer le même contexte produit et documentaire.",
    aboutPara2: "De la culture à la chromatographie jusqu'à l'emballage export, VETRUX fournit une ligne d'approvisionnement unique et responsable pour les partenaires B2B.",
    companyProfile: "Profil de l'entreprise",
    contactEyebrow: 'Contact',
    contactTitle1: 'Discutons de',
    contactTitle2: 'vos exigences',
    emailUs: 'Nous écrire',
    generalInquiry: 'Demande générale',
    salesOem: 'Ventes & OEM/ODM',
    company: 'Entreprise',
    location: 'Localisation',
    ctaTitle: 'Prêt à démarrer une conversation ?',
    ctaBody: 'Parlez-nous de votre projet et notre équipe B2B examinera les détails.',
    sendInquiry: 'Envoyer une demande',
  },

  es: {
    heroEyebrow: 'VETRUX · Yunnan, China',
    heroTitle1: 'De la semilla',
    heroTitle2: 'al aislado',
    heroBody: 'CBD isolate a granel para compradores B2B, con soporte OEM/ODM, documentación lista para exportación y flujos de control de calidad internos desde Yunnan, China.',
    requestCoa: 'Solicitar COA / Ficha técnica',
    getBulkQuote: 'Obtener cotización al por mayor',
    trustHplc: 'HPLC interno',
    trustCoa: 'Soporte COA / SDS',
    trustPackaging: 'Envase a granel 5 kg',
    trustOem: 'OEM/ODM disponible',
    trustExport: 'Soporte documentación exportación',
    buyerAnswersEyebrow: 'Respuestas para compradores',
    buyerAnswersTitle: 'Respuestas sobre abastecimiento de CBD isolate',
    qa: [
      {
        question: '¿Qué fabrica Vetrux?',
        answer: 'Vetrux fabrica CBD isolate a granel y soluciones de materias primas CBD relacionadas para discusiones B2B calificadas, respaldadas por flujos de trabajo de cultivo, extracción, purificación, control de calidad y envasado en Yunnan, China.',
      },
      {
        question: '¿A quién sirve Vetrux?',
        answer: 'Vetrux sirve a compradores B2B, propietarios de marcas, empresas comerciales, socios de canal y equipos de formulación que necesitan CBD isolate a granel, soporte OEM/ODM, soporte de documentación y discusiones de suministro recurrentes.',
      },
      {
        question: '¿Qué documentos pueden solicitar los compradores?',
        answer: 'Los compradores pueden solicitar COA, SDS, informes de prueba, información del producto, factura comercial, lista de empaque y soporte de documentación de exportación. La disponibilidad depende del lote real, los términos del pedido y los resultados de verificación.',
      },
      {
        question: '¿Dónde está ubicado Vetrux?',
        answer: 'Vetrux Biotechnology (Chuxiong) Co., Ltd. está ubicado en Chuxiong, Yunnan, China, con operaciones de materias primas CBD conectadas a flujos de trabajo locales de cultivo, procesamiento, control de calidad y envasado.',
      },
    ],
    scopeEyebrow: 'Alcance comercial',
    scopeTitle1: 'Capacidades de extremo a extremo,',
    scopeTitle2: 'adaptadas a sus necesidades',
    rawMaterialTitle: 'Venta de materias primas CBD',
    rawMaterialBody: 'Servicio a clientes de marca, socios de canal y empresas comerciales con suministro estable de CBD. Suministro estándar, acuerdos a largo plazo y modelos de cooperación dirigida disponibles.',
    rawMaterialCta: 'Explorar suministro',
    oemTitle: 'Servicios OEM / ODM',
    oemBody: 'Soporte de proceso completo desde el abastecimiento de materias primas y el desarrollo de formulaciones hasta la producción, el diseño de envases y la entrega del producto terminado para su marca.',
    oemCta: 'Iniciar un proyecto',
    techTitle: 'Servicios técnicos',
    techBody: 'Gestión de cultivos, optimización de rendimientos, refinamiento del proceso de extracción, control de costos y consultoría de purificación de cannabinoides.',
    techCta: 'Consultar ahora',
    kpiAnalytical: { value: 'HPLC', label: 'Capacidad analítica', sub: 'Soporte control de calidad' },
    kpiDocumentation: { value: 'COA/SDS', label: 'Documentación', sub: 'Según requisitos del pedido' },
    kpiPackaging: { value: '5 kg', label: 'Envase a granel', sub: 'Bolsas PE o aluminio' },
    kpiCooperation: { value: 'OEM/ODM', label: 'Cooperación', sub: 'Soporte proyecto B2B' },
    aboutEyebrow: 'Sobre Vetrux',
    aboutTitle1: 'Calidad arraigada en',
    aboutTitle2: 'cada paso del proceso',
    aboutQuote: 'Tratamos cada kilo de aislado como si se enviara bajo nuestro propio nombre. La trazabilidad no es una etiqueta \u2014 es la forma en que trabaja el equipo.',
    aboutQuoteAttribution: '— Responsable de calidad, VETRUX',
    aboutPara1: 'VETRUX se basa en una sola convicción \u2014 que la revisión consistente de lotes comienza en el campo, no en la línea de envasado. El cultivo, la extracción y los flujos de trabajo internos de control de calidad están conectados para que las discusiones con los compradores puedan hacer referencia al mismo contexto de producto y documentación.',
    aboutPara2: 'Desde el cultivo hasta la cromatografía y el envasado para exportación, VETRUX ofrece una línea de suministro única y responsable para socios B2B.',
    companyProfile: 'Perfil de la empresa',
    contactEyebrow: 'Contacto',
    contactTitle1: 'Hablemos de',
    contactTitle2: 'sus requisitos',
    emailUs: 'Envíenos un correo',
    generalInquiry: 'Consulta general',
    salesOem: 'Ventas & OEM/ODM',
    company: 'Empresa',
    location: 'Ubicación',
    ctaTitle: '¿Listo para iniciar una conversación?',
    ctaBody: 'Cuéntenos sobre su proyecto y nuestro equipo B2B revisará los detalles.',
    sendInquiry: 'Enviar consulta',
  },

  it: {
    heroEyebrow: 'VETRUX · Yunnan, Cina',
    heroTitle1: 'Dal seme',
    heroTitle2: "all'isolato",
    heroBody: 'CBD isolate sfuso per acquirenti B2B, con supporto OEM/ODM, documentazione pronta per l\'export e flussi di controllo qualità interni da Yunnan, Cina.',
    requestCoa: 'Richiedere COA / Scheda tecnica',
    getBulkQuote: 'Richiedere quotazione all\'ingrosso',
    trustHplc: 'HPLC interno',
    trustCoa: 'Supporto COA / SDS',
    trustPackaging: 'Confezionamento sfuso 5 kg',
    trustOem: 'OEM/ODM disponibile',
    trustExport: 'Supporto documentazione export',
    buyerAnswersEyebrow: 'Risposte per acquirenti',
    buyerAnswersTitle: 'Risposte sull\'approvvigionamento di CBD isolate sfuso',
    qa: [
      {
        question: 'Cosa produce Vetrux?',
        answer: 'Vetrux produce CBD isolate sfuso e soluzioni correlate di materie prime CBD per discussioni B2B qualificate, supportate da flussi di lavoro di coltivazione, estrazione, purificazione, controllo qualità e confezionamento a Yunnan, Cina.',
      },
      {
        question: 'Chi serve Vetrux?',
        answer: 'Vetrux serve acquirenti B2B, proprietari di marchi, società commerciali, partner di canale e team di formulazione che necessitano di CBD isolate sfuso, supporto OEM/ODM, supporto documentale e discussioni di fornitura ricorrenti.',
      },
      {
        question: 'Quali documenti possono richiedere gli acquirenti?',
        answer: 'Gli acquirenti possono richiedere COA, SDS, rapporti di test, informazioni sul prodotto, fattura commerciale, lista di imballaggio e supporto per la documentazione di esportazione. La disponibilità dipende dal lotto effettivo, dai termini dell\'ordine e dai risultati della verifica.',
      },
      {
        question: 'Dove ha sede Vetrux?',
        answer: 'Vetrux Biotechnology (Chuxiong) Co., Ltd. ha sede a Chuxiong, Yunnan, Cina, con operazioni di materie prime CBD collegate ai flussi di lavoro locali di coltivazione, lavorazione, controllo qualità e confezionamento.',
      },
    ],
    scopeEyebrow: 'Ambito commerciale',
    scopeTitle1: 'Capacità end-to-end,',
    scopeTitle2: 'su misura per le vostre esigenze',
    rawMaterialTitle: 'Vendita materie prime CBD',
    rawMaterialBody: 'Servizio a clienti di marca, partner di canale e società commerciali con fornitura stabile di CBD. Fornitura standard, accordi a lungo termine e modelli di cooperazione diretta disponibili.',
    rawMaterialCta: 'Esplora l\'offerta',
    oemTitle: 'Servizi OEM / ODM',
    oemBody: 'Supporto completo del processo dall\'approvvigionamento di materie prime e sviluppo di formulazioni fino alla produzione, progettazione degli imballaggi e consegna del prodotto finito per il vostro marchio.',
    oemCta: 'Avviare un progetto',
    techTitle: 'Servizi tecnici',
    techBody: 'Gestione della coltivazione, ottimizzazione delle rese, perfezionamento del processo di estrazione, controllo dei costi e consulenza sulla purificazione dei cannabinoidi.',
    techCta: 'Richiedi ora',
    kpiAnalytical: { value: 'HPLC', label: 'Capacità analitica', sub: 'Supporto controllo qualità' },
    kpiDocumentation: { value: 'COA/SDS', label: 'Documentazione', sub: 'Secondo i requisiti dell\'ordine' },
    kpiPackaging: { value: '5 kg', label: 'Confezionamento sfuso', sub: 'Sacchetti PE o alluminio' },
    kpiCooperation: { value: 'OEM/ODM', label: 'Cooperazione', sub: 'Supporto progetto B2B' },
    aboutEyebrow: 'Chi è Vetrux',
    aboutTitle1: 'Qualità radicata in',
    aboutTitle2: 'ogni fase del processo',
    aboutQuote: 'Trattiamo ogni chilo di isolato come se venisse spedito sotto il nostro nome. La tracciabilità non è un\'etichetta \u2014 è il modo in cui lavora il team.',
    aboutQuoteAttribution: '— Responsabile qualità, VETRUX',
    aboutPara1: 'VETRUX è costruita su una singola convinzione \u2014 che la revisione coerente dei lotti inizia sul campo, non alla linea di imbottigliamento. Coltivazione, estrazione e flussi di lavoro interni di controllo qualità sono collegati in modo che le discussioni con gli acquirenti possano fare riferimento allo stesso contesto di prodotto e documentazione.',
    aboutPara2: 'Dalla coltivazione alla cromatografia fino all\'imballaggio per l\'export, VETRUX fornisce un\'unica linea di fornitura responsabile per i partner B2B.',
    companyProfile: 'Profilo aziendale',
    contactEyebrow: 'Contatti',
    contactTitle1: 'Discutiamo delle',
    contactTitle2: 'vostre esigenze',
    emailUs: 'Scrivici',
    generalInquiry: 'Richiesta generale',
    salesOem: 'Vendite & OEM/ODM',
    company: 'Azienda',
    location: 'Sede',
    ctaTitle: 'Pronti a iniziare una conversazione?',
    ctaBody: 'Raccontateci del vostro progetto e il nostro team B2B esaminerà i dettagli.',
    sendInquiry: 'Invia richiesta',
  },

  pt: {
    heroEyebrow: 'VETRUX · Yunnan, China',
    heroTitle1: 'Da semente',
    heroTitle2: 'ao isolado',
    heroBody: 'CBD isolate a granel para compradores B2B, com suporte OEM/ODM, documentação pronta para exportação e fluxos de controlo de qualidade internos de Yunnan, China.',
    requestCoa: 'Solicitar COA / Ficha técnica',
    getBulkQuote: 'Obter cotação a granel',
    trustHplc: 'HPLC interno',
    trustCoa: 'Suporte COA / SDS',
    trustPackaging: 'Embalagem a granel 5 kg',
    trustOem: 'OEM/ODM disponível',
    trustExport: 'Suporte documentação exportação',
    buyerAnswersEyebrow: 'Respostas para compradores',
    buyerAnswersTitle: 'Respostas sobre abastecimento de CBD isolate',
    qa: [
      {
        question: 'O que a Vetrux fabrica?',
        answer: 'A Vetrux fabrica CBD isolate a granel e soluções de matérias-primas CBD relacionadas para discussões B2B qualificadas, suportadas por fluxos de trabalho de cultivo, extração, purificação, controlo de qualidade e embalagem em Yunnan, China.',
      },
      {
        question: 'A quem a Vetrux serve?',
        answer: 'A Vetrux serve compradores B2B, proprietários de marcas, empresas comerciais, parceiros de canal e equipas de formulação que necessitam de CBD isolate a granel, suporte OEM/ODM, suporte documental e discussões de fornecimento recorrentes.',
      },
      {
        question: 'Que documentos podem os compradores solicitar?',
        answer: 'Os compradores podem solicitar COA, SDS, relatórios de teste, informações do produto, fatura comercial, lista de embalagem e suporte de documentação de exportação. A disponibilidade depende do lote real, dos termos do pedido e dos resultados de verificação.',
      },
      {
        question: 'Onde está sediada a Vetrux?',
        answer: 'A Vetrux Biotechnology (Chuxiong) Co., Ltd. está sediada em Chuxiong, Yunnan, China, com operações de matérias-primas CBD ligadas a fluxos de trabalho locais de cultivo, processamento, controlo de qualidade e embalagem.',
      },
    ],
    scopeEyebrow: 'Âmbito comercial',
    scopeTitle1: 'Capacidades end-to-end,',
    scopeTitle2: 'adaptadas às suas necessidades',
    rawMaterialTitle: 'Venda de matérias-primas CBD',
    rawMaterialBody: 'Serviço a clientes de marca, parceiros de canal e empresas comerciais com fornecimento estável de CBD. Fornecimento padrão, acordos de longo prazo e modelos de cooperação dirigida disponíveis.',
    rawMaterialCta: 'Explorar fornecimento',
    oemTitle: 'Serviços OEM / ODM',
    oemBody: 'Suporte completo do processo desde o abastecimento de matérias-primas e desenvolvimento de formulações até à produção, design de embalagens e entrega do produto acabado para a sua marca.',
    oemCta: 'Iniciar um projeto',
    techTitle: 'Serviços técnicos',
    techBody: 'Gestão de cultivo, otimização de rendimentos, refinamento do processo de extração, controlo de custos e consultoria de purificação de canabinoides.',
    techCta: 'Consultar agora',
    kpiAnalytical: { value: 'HPLC', label: 'Capacidade analítica', sub: 'Suporte controlo de qualidade' },
    kpiDocumentation: { value: 'COA/SDS', label: 'Documentação', sub: 'Conforme requisitos do pedido' },
    kpiPackaging: { value: '5 kg', label: 'Embalagem a granel', sub: 'Sacos PE ou alumínio' },
    kpiCooperation: { value: 'OEM/ODM', label: 'Cooperação', sub: 'Suporte projeto B2B' },
    aboutEyebrow: 'Sobre a Vetrux',
    aboutTitle1: 'Qualidade enraizada em',
    aboutTitle2: 'cada etapa do processo',
    aboutQuote: 'Tratamos cada quilo de isolado como se fosse expedido sob o nosso próprio nome. A rastreabilidade não é um rótulo \u2014 é a forma como a equipa trabalha.',
    aboutQuoteAttribution: '— Responsável de qualidade, VETRUX',
    aboutPara1: 'A VETRUX assenta numa única convicção \u2014 que a revisão consistente de lotes começa no campo, não na linha de engarrafamento. O cultivo, a extração e os fluxos de trabalho internos de controlo de qualidade estão ligados para que as discussões com os compradores possam referenciar o mesmo contexto de produto e documentação.',
    aboutPara2: 'Do cultivo à cromatografia até à embalagem para exportação, a VETRUX fornece uma linha de abastecimento única e responsável para parceiros B2B.',
    companyProfile: 'Perfil da empresa',
    contactEyebrow: 'Contacto',
    contactTitle1: 'Vamos discutir',
    contactTitle2: 'os seus requisitos',
    emailUs: 'Enviar e-mail',
    generalInquiry: 'Consulta geral',
    salesOem: 'Vendas & OEM/ODM',
    company: 'Empresa',
    location: 'Localização',
    ctaTitle: 'Pronto para iniciar uma conversa?',
    ctaBody: 'Fale-nos do seu projeto e a nossa equipa B2B analisará os detalhes.',
    sendInquiry: 'Enviar consulta',
  },

  ja: {
    heroEyebrow: 'VETRUX · 中国・雲南省',
    heroTitle1: '種から',
    heroTitle2: 'アイソレートへ',
    heroBody: 'B2B購買担当者向けのバルクCBDアイソレート。OEM/ODMサポート、輸出対応ドキュメント、中国・雲南省からの社内品質管理フローを提供しています。',
    requestCoa: 'COA / 仕様書を請求する',
    getBulkQuote: 'バルク見積もりを取得',
    trustHplc: '社内HPLC分析',
    trustCoa: 'COA / SDSサポート',
    trustPackaging: '5kgバルク包装',
    trustOem: 'OEM/ODM対応',
    trustExport: '輸出書類サポート',
    buyerAnswersEyebrow: '購買担当者向けQ&A',
    buyerAnswersTitle: 'バルクCBDアイソレート調達に関するQ&A',
    qa: [
      {
        question: 'Vetruxは何を製造していますか？',
        answer: 'Vetruxは、中国・雲南省における栽培、抽出、精製、品質管理、包装のワークフローに支えられた、適格なB2B商談向けのバルクCBDアイソレートおよび関連CBD原料ソリューションを製造しています。',
      },
      {
        question: 'Vetruxはどのような顧客に対応していますか？',
        answer: 'Vetruxは、バルクCBDアイソレート、OEM/ODMサポート、ドキュメントサポート、継続的な供給商談を必要とするB2B購買担当者、ブランドオーナー、商社、チャネルパートナー、処方チームに対応しています。',
      },
      {
        question: '購買担当者はどのような書類を請求できますか？',
        answer: 'COA、SDS、試験報告書、製品情報、商業送り状、梱包明細書、輸出書類サポートを請求できます。提供可否は実際のロット、注文条件、確認結果によって異なります。',
      },
      {
        question: 'Vetruxはどこに拠点を置いていますか？',
        answer: 'Vetrux Biotechnology（楚雄）Co., Ltd.は中国・雲南省楚雄市に拠点を置き、CBD原料事業は地域の栽培、加工、品質管理、包装ワークフローと連携しています。',
      },
    ],
    scopeEyebrow: '事業範囲',
    scopeTitle1: 'エンドツーエンドの対応力、',
    scopeTitle2: 'お客様のニーズに合わせて',
    rawMaterialTitle: 'CBD原料販売',
    rawMaterialBody: 'ブランドクライアント、チャネルパートナー、商社に対して安定したCBD供給を提供しています。標準供給、長期契約、指定協力モデルに対応しています。',
    rawMaterialCta: '供給内容を見る',
    oemTitle: 'OEM / ODMサービス',
    oemBody: '原料調達・処方開発から製造、パッケージデザイン、完成品納品まで、貴社ブランドのためのフルプロセスサポートを提供しています。',
    oemCta: 'プロジェクトを開始する',
    techTitle: '技術サービス',
    techBody: '栽培管理、収量最適化、抽出プロセスの改善、コスト管理、カンナビノイド精製コンサルティングを提供しています。',
    techCta: '今すぐ問い合わせる',
    kpiAnalytical: { value: 'HPLC', label: '分析能力', sub: '品質管理サポート' },
    kpiDocumentation: { value: 'COA/SDS', label: 'ドキュメント', sub: '注文要件に応じて' },
    kpiPackaging: { value: '5 kg', label: 'バルク包装', sub: 'PEまたはアルミ箔袋' },
    kpiCooperation: { value: 'OEM/ODM', label: '協力体制', sub: 'B2Bプロジェクト対応' },
    aboutEyebrow: 'Vetruxについて',
    aboutTitle1: 'プロセスの',
    aboutTitle2: 'すべての工程に根ざした品質',
    aboutQuote: '私たちは、すべてのアイソレートを自社名で出荷するかのように扱っています。トレーサビリティはラベルではなく、チームの働き方そのものです。',
    aboutQuoteAttribution: '— 品質責任者、VETRUX',
    aboutPara1: 'VETRUXは一つの信念のもとに構築されています \u2014 一貫したロットレビューは、瓶詰めラインではなく、現場から始まるという信念です。栽培、抽出、社内品質管理ワークフローが連携しており、購買担当者との商談において同一の製品・ドキュメントコンテキストを参照できます。',
    aboutPara2: '栽培からクロマトグラフィー、輸出包装まで、VETRUXはB2Bパートナーに対して一元的で責任ある供給ラインを提供しています。',
    companyProfile: '会社概要',
    contactEyebrow: 'お問い合わせ',
    contactTitle1: 'ご要件について',
    contactTitle2: 'ご相談ください',
    emailUs: 'メールで問い合わせる',
    generalInquiry: '一般お問い合わせ',
    salesOem: '営業・OEM/ODM',
    company: '会社',
    location: '所在地',
    ctaTitle: 'ご商談を始めませんか？',
    ctaBody: 'プロジェクトの詳細をお知らせください。B2Bチームが内容を確認いたします。',
    sendInquiry: 'お問い合わせを送信',
  },

  fi: {
    heroEyebrow: 'VETRUX · Yunnan, Kiina',
    heroTitle1: 'Siemenestä',
    heroTitle2: 'isolaatiksi',
    heroBody: 'Bulk-CBD-isolaattia B2B-ostajille, OEM/ODM-tuella, vientikelpoinen dokumentaatio ja sisäiset laadunvalvontaprosessit Yunnanista, Kiinasta.',
    requestCoa: 'Pyydä COA / tuotetiedote',
    getBulkQuote: 'Pyydä tukkutarjous',
    trustHplc: 'Sisäinen HPLC-analyysi',
    trustCoa: 'COA / SDS-tuki',
    trustPackaging: '5 kg bulk-pakkaus',
    trustOem: 'OEM/ODM saatavilla',
    trustExport: 'Vientidokumentaatiotuki',
    buyerAnswersEyebrow: 'Ostajan kysymykset',
    buyerAnswersTitle: 'Vastauksia bulk-CBD-isolaatin hankintaan',
    qa: [
      {
        question: 'Mitä Vetrux valmistaa?',
        answer: 'Vetrux valmistaa bulk-CBD-isolaattia ja siihen liittyviä CBD-raaka-aineratkaisuja kvalifioituihin B2B-neuvotteluihin, tuettuna viljely-, uutto-, puhdistus-, laadunvalvonta- ja pakkausprosesseilla Yunnanissa, Kiinassa.',
      },
      {
        question: 'Ketä Vetrux palvelee?',
        answer: 'Vetrux palvelee B2B-ostajia, brändinomistajia, kauppayhtiöitä, kanavapartnereita ja formulointitiimejä, jotka tarvitsevat bulk-CBD-isolaattia, OEM/ODM-tukea, dokumentaatiotukea ja toistuvia toimitusneuvotteluja.',
      },
      {
        question: 'Mitä asiakirjoja ostajat voivat pyytää?',
        answer: 'Ostajat voivat pyytää COA:ta, SDS:ää, testiraportteja, tuotetietoja, kauppalaskua, pakkausluetteloa ja vientidokumentaatiotukea. Saatavuus riippuu todellisesta erästä, tilausehdoista ja tarkistustuloksista.',
      },
      {
        question: 'Missä Vetrux sijaitsee?',
        answer: 'Vetrux Biotechnology (Chuxiong) Co., Ltd. sijaitsee Chuxiongissa, Yunnanin maakunnassa, Kiinassa. CBD-raaka-ainetoiminnot ovat yhteydessä paikallisiin viljely-, käsittely-, laadunvalvonta- ja pakkausprosesseihin.',
      },
    ],
    scopeEyebrow: 'Liiketoiminta-alue',
    scopeTitle1: 'Kattavat valmiudet,',
    scopeTitle2: 'räätälöity tarpeisiinne',
    rawMaterialTitle: 'CBD-raaka-ainemyynti',
    rawMaterialBody: 'Palvelemme brändiyhtiöitä, kanavapartnereita ja kauppayhtiöitä vakaalla CBD-toimituksella. Saatavilla vakiotoimitus, pitkäaikaiset sopimukset ja ohjatut yhteistyömallit.',
    rawMaterialCta: 'Tutustu toimitukseen',
    oemTitle: 'OEM / ODM-palvelut',
    oemBody: 'Täyden prosessin tuki raaka-ainehankinnasta ja formulaatiokehityksestä tuotantoon, pakkaussuunnitteluun ja valmiiden tuotteiden toimitukseen brändillenne.',
    oemCta: 'Aloita projekti',
    techTitle: 'Tekniset palvelut',
    techBody: 'Viljelynhallinta, sadonoptiminti, uuttoprosessin kehittäminen, kustannusten hallinta ja kannabinoidien puhdistuskonsultointi.',
    techCta: 'Tiedustele nyt',
    kpiAnalytical: { value: 'HPLC', label: 'Analyyttinen kapasiteetti', sub: 'Laadunvalvontatuki' },
    kpiDocumentation: { value: 'COA/SDS', label: 'Dokumentaatio', sub: 'Tilausvaatimusten mukaan' },
    kpiPackaging: { value: '5 kg', label: 'Bulk-pakkaus', sub: 'PE- tai alumiinifoliipussit' },
    kpiCooperation: { value: 'OEM/ODM', label: 'Yhteistyö', sub: 'B2B-projektituki' },
    aboutEyebrow: 'Tietoa Vetruxista',
    aboutTitle1: 'Laatu juurtuneena',
    aboutTitle2: 'jokaiseen prosessin vaiheeseen',
    aboutQuote: 'Käsittelemme jokaista isolaattikiloa kuin se lähetettäisiin omalla nimellemme. Jäljitettävyys ei ole etiketti \u2014 se on tavan, jolla tiimi työskentelee.',
    aboutQuoteAttribution: '— Laatupäällikkö, VETRUX',
    aboutPara1: 'VETRUX on rakennettu yhden vakaumuksen varaan \u2014 että johdonmukainen erätarkastus alkaa pellolta, ei pullotuslinjaston päässä. Viljely, uutto ja sisäiset laadunvalvontaprosessit on kytketty toisiinsa niin, että ostajaneuvotteluissa voidaan viitata samaan tuote- ja dokumentaatiokontekstiin.',
    aboutPara2: 'Viljelystä kromatografiaan ja vientipakkaukseen asti VETRUX tarjoaa yhden vastuullisen toimituslinjan B2B-kumppaneille.',
    companyProfile: 'Yritysprofiili',
    contactEyebrow: 'Yhteystiedot',
    contactTitle1: 'Keskustellaan',
    contactTitle2: 'vaatimuksistanne',
    emailUs: 'Lähetä sähköpostia',
    generalInquiry: 'Yleinen tiedustelu',
    salesOem: 'Myynti & OEM/ODM',
    company: 'Yritys',
    location: 'Sijainti',
    ctaTitle: 'Valmiina aloittamaan keskustelun?',
    ctaBody: 'Kerro meille projektistasi ja B2B-tiimimme käy yksityiskohdat läpi.',
    sendInquiry: 'Lähetä tiedustelu',
  },
};
